{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.6.6/material-icons-extended-1.6.6.module",
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.6.aar",
          "size": 35720998,
          "sha512": "8811b957a59a75c0cf936660758a81494d9ed9e761e2bb94d4427dfc784679b7cedac7ae86d1ae491e3f60f0d7045f83720d37869fc6247d6e7a9e3ccaab294b",
          "sha256": "4358f80ecb7efb811c6bd6aaeacf235dbbd2a6e4f8f9f82eb6a5aaab944b2e8c",
          "sha1": "bf3f60123a141fc062b8883bac076e145213a854",
          "md5": "a542d86194c23480a6e5cbfbebcc0462"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.6.aar",
          "size": 35720998,
          "sha512": "8811b957a59a75c0cf936660758a81494d9ed9e761e2bb94d4427dfc784679b7cedac7ae86d1ae491e3f60f0d7045f83720d37869fc6247d6e7a9e3ccaab294b",
          "sha256": "4358f80ecb7efb811c6bd6aaeacf235dbbd2a6e4f8f9f82eb6a5aaab944b2e8c",
          "sha1": "bf3f60123a141fc062b8883bac076e145213a854",
          "md5": "a542d86194c23480a6e5cbfbebcc0462"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "material-icons-extended is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-android-1.6.6-sources.jar",
          "url": "material-icons-extended-android-1.6.6-sources.jar",
          "size": 12085941,
          "sha512": "8052018ed087abb947f6063970211a78b1ca963fc3ba045bd07cd61e5817a5a3ebc61e2214ed1b88257011e5649899dfa3ab49d51b305d2dcf9b1971fc13bab5",
          "sha256": "9b22840d9d5ec83fca54783df66640c0e2d76bb164687d654c23bcc6c02f3a96",
          "sha1": "4c74984f208526fde6a4ad0d78d00a8d33cbcce0",
          "md5": "9eb38b15d560c68fa1c277d4dbd85fe9"
        }
      ]
    }
  ]
}